### ISSUE TITLE
Crash Issue in Android Oreo

### ISSUE THREAD

**Issue by akashpatra** [akashpatra/odiapurana#13]
App getting crashed in Android Oreo.

**Below stacktrace:**
                                                                         E/AndroidRuntime: FATAL EXCEPTION: main
                                                                         Process: in.co.trapps.odiapurana, PID: 21547
                                                                         android.view.InflateException: Binary XML file line #59: Binary XML file line #59: Error inflating class TextView
                                                                         Caused by: android.view.InflateException: Binary XML file line #59: Error inflating class TextView
                                                                         Caused by: java.lang.IndexOutOfBoundsException
                                                                             at android.content.res.StringBlock.nativeGetString(Native Method)
                                                                             at android.content.res.StringBlock.get(StringBlock.java:82)
                                                                             at android.content.res.AssetManager.getPooledStringForCookie(AssetManager.java:332)
                                                                             at android.content.res.TypedArray.loadStringValueAt(TypedArray.java:1272)
                                                                             at android.content.res.TypedArray.getText(TypedArray.java:175)
                                                                             at android.widget.TextView.<init>(TextView.java:1151)
                                                                             at android.widget.TextView.<init>(TextView.java:824)
                                                                             at android.support.v7.widget.AppCompatTextView.<init>(AppCompatTextView.java:62)
                                                                             at android.support.v7.widget.AppCompatTextView.<init>(AppCompatTextView.java:58)
                                                                             at android.support.v7.app.AppCompatViewInflater.createView(AppCompatViewInflater.java:103)
                                                                             at android.support.v7.app.AppCompatDelegateImplV9.createView(AppCompatDelegateImplV9.java:1029)
                                                                             at android.support.v7.app.AppCompatDelegateImplV9.onCreateView(AppCompatDelegateImplV9.java:1087)
                                                                             at android.support.v4.view.LayoutInflaterCompatHC$FactoryWrapperHC.onCreateView(LayoutInflaterCompatHC.java:47)
                                                                             at android.view.LayoutInflater$FactoryMerger.onCreateView(LayoutInflater.java:189)
                                                                             at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:772)
                                                                             at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:730)
                                                                             at android.view.LayoutInflater.rInflate(LayoutInflater.java:863)
                                                                             at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
                                                                             at android.view.LayoutInflater.rInflate(LayoutInflater.java:866)
                                                                             at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
                                                                             at android.view.LayoutInflater.rInflate(LayoutInflater.java:866)
                                                                             at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
                                                                             at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
                                                                             at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
                                                                             at in.co.trapps.odiapurana.fragments.MusicServiceFragment.onCreateView(MusicServiceFragment.java:99)
                                                                             at android.support.v4.app.Fragment.performCreateView(Fragment.java:2192)
                                                                             at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1299)
                                                                             at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1528)
                                                                             at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1595)
                                                                             at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:758)
                                                                             at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2363)
                                                                             at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2149)
                                                                             at android.support.v4.app.FragmentManagerImpl.optimizeAndExecuteOps(FragmentManager.java:2103)
                                                                             at android.support.v4.app.FragmentManagerImpl.execSingleAction(FragmentManager.java:1984)
                                                                             at android.support.v4.app.BackStackRecord.commitNowAllowingStateLoss(BackStackRecord.java:626)
                                                                             at android.support.v4.app.FragmentPagerAdapter.finishUpdate(FragmentPagerAdapter.java:143)
                                                                             at android.support.v4.view.ViewPager.populate(ViewPager.java:1268)
                                                                             at android.support.v4.view.ViewPager.populate(ViewPager.java:1116)
                                                                             at android.support.v4.view.ViewPager.onMeasure(ViewPager.java:1642)
                                                                             at android.view.View.measure(View.java:22104)
                                                                             at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6584)
                                                                             at android.support.design.widget.CoordinatorLayout.onMeasureChild(CoordinatorLayout.java:714)
                                                                             at android.support.design.widget.HeaderScrollingViewBehavior.onMeasureChild(HeaderScrollingViewBehavior.java:90)
                                                                             at android.support.design.widget.AppBarLayout$ScrollingViewBehavior.onMeasureChild(AppBarLayout.java:1391)
                                                                             at android.support.design.widget.CoordinatorLayout.onMeasure(CoordinatorLayout.java:784)
                                                                             at android.view.View.measure(View.java:22104)
E/AndroidRuntime:     at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6584)
                                                                             at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
                                                                             at android.support.v7.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:139)
                                                                             at android.view.View.measure(View.java:22104)
                                                                             at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6584)
                                                                             at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1514)
                                                                             at android.widget.LinearLayout.measureVertical(LinearLayout.java:806)
                                                                             at android.widget.LinearLayout.onMeasure(LinearLayout.java:685)
                                                                             at android.view.View.measure(View.java:22104)
                                                                             at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6584)
                                                                             at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
                                                                             at android.view.View.measure(View.java:22104)
                                                                             at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6584)
                                                                             at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1514)
                                                                             at android.widget.LinearLayout.measureVertical(LinearLayout.java:806)
                                                                             at android.widget.LinearLayout.onMeasure(LinearLayout.java:685)
                                                                             at android.view.View.measure(View.java:22104)
                                                                             at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6584)
                                                                             at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
                                                                             at com.android.internal.policy.DecorView.onMeasure(DecorView.java:722)
                                                                             at android.view.View.measure(View.java:22104)
                                                                             at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2447)
                                                                             at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1528)
                                                                             at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1781)
                                                                             at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1416)
                                                                             at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6845)
                                                                             at android.view.Choreographer$CallbackRecord.run(Choreographer.java:966)
                                                                             at android.view.Choreographer.doCallbacks(Choreographer.java:778)
                                                                             at android.view.Choreographer.doFrame(Choreographer.java:713)
                                                                             at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:952)
                                                                             at android.os.Handler.handleCallback(Handler.java:789)
                                                                             at android.os.Handler.dispatchMessage(Handler.java:98)
                                                                             at android.os.Looper.loop(Looper.java:164)
                                                                             at android.app.ActivityThread.main(ActivityThread.java:6798)
                                                                             at java.lang.reflect.Method.invoke(Native Method)
                                                                             at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
                                                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)

**Comment by akashpatra** [comment]
Got lead from [here](https://stackoverflow.com/questions/49940524/getstringr-string-res-name-giving-java-lang-indexoutofboundsexception). Need to break the long string in strings.xml to string-array.
