### ISSUE TITLE
App Crashes in FullScreen mode of YouTube View 

### ISSUE THREAD

**Issue by akashpatra** [akashpatra/odiapurana#3]
A User has reported following crash log:

java.lang.NullPointerException: 
  at in.co.trapps.odiapurana.fragments.MusicServiceFragment$1.run (MusicServiceFragment.java:67)
  at android.os.Handler.handleCallback (Handler.java:739)
  at android.os.Handler.dispatchMessage (Handler.java:95)
  at android.os.Looper.loop (Looper.java:152)
  at android.app.ActivityThread.main (ActivityThread.java:5497)
  at java.lang.reflect.Method.invoke (Native Method)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:726)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:616)

**Comment by akashpatra** [comment]
Added code Fix after going through below trace.

Debug StackTrace:

01-21 08:50:50.410 25984-25984/in.co.trapps.odiapurana D/Purana: LaxmiPuranaFragment >> onPause
01-21 08:50:50.410 25984-25984/in.co.trapps.odiapurana D/Purana: LaxmiPuranaVideoFragment >> onPause
01-21 08:50:50.545 25984-25984/in.co.trapps.odiapurana D/Purana: LaxmiPuranaFragment >> onStop
01-21 08:50:50.545 25984-25984/in.co.trapps.odiapurana D/Purana: LaxmiPuranaVideoFragment >> onStop
01-21 08:50:50.545 25984-25984/in.co.trapps.odiapurana D/Purana: LaxmiPuranaFragment >> onDestroyView
01-21 08:50:50.545 25984-25984/in.co.trapps.odiapurana D/Purana: LaxmiPuranaFragment >> onDestroy
01-21 08:50:50.575 25984-25984/in.co.trapps.odiapurana D/Purana: LaxmiPuranaVideoFragment >> onDestroyView
01-21 08:50:50.580 25984-25984/in.co.trapps.odiapurana D/Purana: LaxmiPuranaVideoFragment >> onDestroy
01-21 08:50:50.580 25984-25984/in.co.trapps.odiapurana D/Purana: MusicServiceFragment >> onDestroy
01-21 08:50:50.685 25984-25984/in.co.trapps.odiapurana D/Purana: LaxmiPuranaFragment >> onCreate
01-21 08:50:50.685 25984-25984/in.co.trapps.odiapurana D/Purana: LaxmiPuranaVideoFragment >> onCreate
01-21 08:50:50.685 25984-25984/in.co.trapps.odiapurana D/Purana: MusicServiceFragment >> onCreate
01-21 08:50:50.690 25984-25984/in.co.trapps.odiapurana D/Purana: MainAct >> onCreate
01-21 08:50:50.710 25984-25984/in.co.trapps.odiapurana D/Purana: LaxmiPuranaFragment >> onCreateView
01-21 08:50:50.715 25984-25984/in.co.trapps.odiapurana D/Purana: LaxmiPuranaFragment >> onViewCreated
01-21 08:50:50.715 25984-25984/in.co.trapps.odiapurana D/Purana: LaxmiPuranaVideoFragment >> onCreateView
01-21 08:50:50.720 25984-25984/in.co.trapps.odiapurana D/Purana: LaxmiPuranaVideoFragment >> onViewCreated
01-21 08:50:50.720 25984-25984/in.co.trapps.odiapurana D/Purana: LaxmiPuranaFragment >> onStart
01-21 08:50:50.720 25984-25984/in.co.trapps.odiapurana D/Purana: LaxmiPuranaVideoFragment >> onStart
01-21 08:50:50.720 25984-25984/in.co.trapps.odiapurana D/Purana: LaxmiPuranaFragment >> onResume
01-21 08:50:50.720 25984-25984/in.co.trapps.odiapurana D/Purana: LaxmiPuranaVideoFragment >> onResume
01-21 08:50:50.750 25984-25984/in.co.trapps.odiapurana D/Purana: LaxmiPuranaVideoFragment >> setUserVisibleHint >> Flag: false
01-21 08:50:50.750 25984-25984/in.co.trapps.odiapurana D/Purana: LaxmiPuranaVideoFragment >> setUserVisibleHint >> Flag: true

01-21 08:50:51.005 25984-25984/in.co.trapps.odiapurana E/AndroidRuntime: FATAL EXCEPTION: main
                                                                         Process: in.co.trapps.odiapurana, PID: 25984
                                                                         java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.TextView.setText(java.lang.CharSequence)' on a null object reference
                                                                             at in.co.trapps.odiapurana.fragments.MusicServiceFragment$1.run(MusicServiceFragment.java:67)
                                                                             at android.os.Handler.handleCallback(Handler.java:739)
                                                                             at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                             at android.os.Looper.loop(Looper.java:148)
                                                                             at android.app.ActivityThread.main(ActivityThread.java:7331)
                                                                             at java.lang.reflect.Method.invoke(Native Method)
                                                                             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
                                                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
