### ISSUE TITLE
Crash Issue on Rotation at Seekbar

### ISSUE THREAD

**Issue by akashpatra** [akashpatra/odiapurana#9]
App getting crashed when rotation occurs and user try to play with seekbar.

**Below stacktrace:**
java.lang.NullPointerException: Attempt to invoke virtual method 'void android.media.MediaPlayer.seekTo(int)' on a null object reference
                                                                             at in.co.trapps.odiapurana.service.MusicService.seekTo(MusicService.java:150)
                                                                             at in.co.trapps.odiapurana.fragments.MusicServiceFragment.onStopTrackingTouch(MusicServiceFragment.java:233)
                                                                             at android.widget.SeekBar.onStopTrackingTouch(SeekBar.java:123)
                                                                             at android.widget.AbsSeekBar.onTouchEvent(AbsSeekBar.java:791)
                                                                             at android.view.View.dispatchTouchEvent(View.java:11776)
                                                                             at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2965)
                                                                             at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2650)
                                                                             at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2965)
                                                                             at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2650)
                                                                             at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2965)
                                                                             at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2650)
                                                                             at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2965)
                                                                             at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2650)
                                                                             at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2965)
                                                                             at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2650)
                                                                             at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2965)
                                                                             at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2650)
                                                                             at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2965)
                                                                             at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2650)
                                                                             at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2965)
                                                                             at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2650)
                                                                             at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2965)
                                                                             at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2650)
                                                                             at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:446)
                                                                             at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1848)
                                                                             at android.app.Activity.dispatchTouchEvent(Activity.java:3315)
                                                                             at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:71)
                                                                             at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:71)
                                                                             at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:408)
                                                                             at android.view.View.dispatchPointerEvent(View.java:12015)
                                                                             at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4855)
                                                                             at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4638)
                                                                             at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4169)
                                                                             at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4222)
                                                                             at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4188)
                                                                             at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4315)
                                                                             at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4196)
                                                                             at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4372)
                                                                             at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4169)
                                                                             at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4222)
                                                                             at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4188)
                                                                             at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4196)
                                                                             at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4169)
                                                                             at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:6743)
                                                                             at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:6717)
                                                                             at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:6663)
                                                                             at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6846)
                                                                             at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:186)
                                                                             at android.os.MessageQueue.nativePollOnce(Native Method)
                                                                             at android.os.MessageQueue.next(MessageQueue.java:325)
01-28 12:45:46.513 26468-26468/in.co.trapps.odiapurana E/AndroidRuntime:     at android.os.Looper.loop(Looper.java:142)
                                                                             at android.app.ActivityThread.main(ActivityThread.java:6809)
                                                                             at java.lang.reflect.Method.invoke(Native Method)
                                                                             at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
                                                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)

**Comment by akashpatra** [comment]
Need to fix by handling rotation. For quick resolution, stopping the rotation by restricting to portrait mode in Manifest.
